# Generated by Django 5.2.3 on 2025-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Unique code for each batch.', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Name of the brand or manufacturer.', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Capsule', 'Capsule'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., 500mg tablet, 5ml/5mg syrup', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Shelf 3, Box A, Fridge', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price at which the item was purchased.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price at which the item is sold.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_info',
            field=models.TextField(blank=True, help_text='e.g., Keep refrigerated, Store away from sunlight'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Name of the supplier.', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
