# Generated by Django 5.2.3 on 2025-06-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='batch_number',
            new_name='code',
        ),
    ]
