# Generated by Django 5.2.3 on 2025-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_batch_number_medicine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Pill', 'Pill'), ('Suppository', 'Suppository'), ('Lozenge', 'Lozenge'), ('Powder (g)', 'Powder (g)'), ('ml (milliliter)', 'ml (milliliter)'), ('l (liter)', 'l (liter)'), ('Drop or gtt', 'Drop or gtt'), ('Vial', 'Vial'), ('Ampoule', 'Ampoule'), ('Syringe', 'Syringe'), ('IU (International Unit)', 'IU (International Unit)'), ('Tube (g)', 'Tube (g)'), ('Spray (ml)', 'Spray (ml)'), ('Patch', 'Patch'), ('Bottle (ml)', 'Bottle (ml)'), ('Strip', 'Strip'), ('Blister Pack', 'Blister Pack'), ('Box', 'Box'), ('Carton', 'Carton'), ('Kit', 'Kit'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
