# Generated by Django 5.2.3 on 2025-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='base_unit',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Pill', 'Pill'), ('Suppository', 'Suppository'), ('Lozenge', 'Lozenge'), ('Gram (g)', 'Gram (g)'), ('Milliliter (ml)', 'Milliliter (ml)'), ('Liter (l)', 'Liter (l)'), ('Drop (gtt)', 'Drop (gtt)'), ('Vial', 'Vial'), ('Ampoule', 'Ampoule'), ('Syringe', 'Syringe'), ('IU', 'IU (International Unit)'), ('Tube', 'Tube'), ('Spray', 'Spray'), ('Patch', 'Patch'), ('Other', 'Other')], default='Tablet', help_text='The smallest unit of the medicine.', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='package_type',
            field=models.CharField(blank=True, help_text='e.g., Bottle, Box, Strip, Blister Pack', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_per_package',
            field=models.PositiveIntegerField(default=1, help_text='Number of base units per package (e.g., 30 for a bottle of 30 tablets).'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The total number of packages in stock.'),
        ),
    ]
