# Generated by Django 5.2.3 on 2025-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_medicine_category_medicine_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the medicine.', max_length=50),
        ),
    ]
