# Generated by Django 5.2.3 on 2025-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_medicine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='base_unit',
            field=models.CharField(choices=[('Tablet', 'ဆေးပြား'), ('Capsule', 'ဆေးတောင့်'), ('Pill', 'ဆေးလုံး'), ('Suppository', 'စအိုထည့်ဆေး'), ('Lozenge', 'ငုံဆေး'), ('Gram (g)', 'ဂရမ် (အမှုန့်)'), ('ml (milliliter)', 'မီလီလီတာ'), ('l (liter)', 'လီတာ'), ('Drop or gtt', 'ဆေးရည်စက်'), ('Vial', 'ဆေးပုလင်း'), ('Ampoule', 'ဆေးထိုးပုလင်း'), ('Syringe', 'ဆေးထိုးပြွန်'), ('IU', 'IU (International Unit)'), ('Tube', 'ပြွန် (ဂရမ်)'), ('Spray', 'ဖျန်းဆေး (မီလီလီတာ)'), ('Patch', 'ကပ်ခွာ'), ('Bottle', 'ပုလင်း (မီလီလီတာ)'), ('Strip', 'ဆေးကတ်'), ('Blister Pack', 'ဆေးကတ်'), ('Box', 'ဘူး'), ('Carton', 'ကတ်တန်'), ('Kit', 'Kit'), ('Other', 'အခြား')], default='Tablet', help_text='The smallest unit of the medicine.', max_length=50),
        ),
    ]
