# Generated by Django 5.2.3 on 2025-06-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_medicine_base_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='base_unit',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Pill', 'Pill'), ('Suppository', 'Suppository'), ('Lozenge', 'Lozenge'), ('Powder (g)', 'Powder (g)'), ('ml (milliliter)', 'ml (milliliter)'), ('l (liter)', 'l (liter)'), ('Drop or gtt', 'Drop or gtt'), ('Vial', 'Vial'), ('Ampoule', 'Ampoule'), ('Syringe', 'Syringe'), ('IU (International Unit)', 'IU (International Unit)'), ('Tube (g)', 'Tube (g)'), ('Spray (ml)', 'Spray (ml)'), ('Patch', 'Patch'), ('Bottle (ml)', 'Bottle (ml)'), ('Strip', 'Strip'), ('Blister Pack', 'Blister Pack'), ('Box', 'Box'), ('Carton', 'Carton'), ('Kit', 'Kit'), ('Other', 'Other')], default='Tablet', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dosage Form'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(verbose_name='Expire Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='package_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Buy Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_per_package',
            field=models.PositiveIntegerField(default=1, verbose_name='Units/Pkg'),
        ),
    ]
