# Generated by Django 5.2.3 on 2025-06-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_medicine_base_unit_medicine_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='selling_price',
            field=models.IntegerField(default=0, verbose_name='Sell Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.IntegerField(),
        ),
    ]
