# Generated by Django 5.2.3 on 2025-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_medicine_brand_name_alter_medicine_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Painkillers', 'Painkillers (Analgesics)'), ('Antibiotics', 'Antibiotics'), ('Antipyretics', 'Antipyretics (fever reducers)'), ('Antihistamines', 'Antihistamines (allergy)'), ('Antacids', 'Antacids (gastric)'), ('Antidiabetics', 'Antidiabetics'), ('Antihypertensives', 'Antihypertensives'), ('Cough & Cold', 'Cough & Cold'), ('Antiseptics', 'Antiseptics'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Medicine Type'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dosage Form'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
