# Generated by Django 5.2.3 on 2025-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_medicine_medicine_type_alter_medicine_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
    ]
