# Generated by Django 5.2.3 on 2025-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_sale_customer_address_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Painkillers', 'Painkillers (Analgesics)'), ('Antibiotics', 'Antibiotics'), ('Antipyretics', 'Antipyretics (fever reducers)'), ('Antihistamines', 'Antihistamines (allergy)'), ('Antacids', 'Antacids (gastric)'), ('Antidiabetics', 'Antidiabetics'), ('Antihypertensives', 'Antihypertensives'), ('Cough & Cold', 'Cough & Cold'), ('Antiseptics', 'Antiseptics'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Category'),
        ),
    ]
