# Generated by Django 5.2.3 on 2025-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_medicinetype_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Painkillers', 'Painkillers (Analgesics)'), ('Antibiotics', 'Antibiotics'), ('Antipyretics', 'Antipyretics (fever reducers)'), ('Antihistamines', 'Antihistamines (allergy)'), ('Antacids', 'Antacids (gastric)'), ('Antidiabetics', 'Antidiabetics'), ('Antihypertensives', 'Antihypertensives'), ('Cough & Cold', 'Cough & Cold'), ('Antiseptics', 'Antiseptics'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='MedicineType',
        ),
    ]
