# Generated by Django 5.2.3 on 2025-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_medicine_medicine_type_medicine_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NC Pharmacy', max_length=200)),
                ('address', models.TextField(default='123 Main Street, Anytown, USA 12345')),
                ('phone_number', models.CharField(default='(123) 456-7890', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Pharmacy Info',
            },
        ),
    ]
