# Generated by Django 5.2.3 on 2025-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('boss', 'Boss'), ('staff', 'Staff')], max_length=10),
        ),
    ]
