# Generated by Django 5.2.3 on 2025-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_sale_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinfo',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Optional second phone number.', max_length=20, null=True),
        ),
    ]
