# Generated by Django 4.2.23 on 2025-08-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_pharmacyinfo_phone_number_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Instrument', 'Instrument'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Category'),
        ),
    ]
