# Generated by Django 4.2.23 on 2025-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chemical Name'),
        ),
    ]
